// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Ay3w2qM-sguKkaoTvCXEIedbNxpFKvg',
    appId: '1:671548251869:web:5ee9ecdd4aee39a0dbc534',
    messagingSenderId: '671548251869',
    projectId: 'robin-aad0d',
    authDomain: 'robin-aad0d.firebaseapp.com',
    storageBucket: 'robin-aad0d.firebasestorage.app',
    measurementId: 'G-XZ1K2RQ3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxFlnF2rgthjF2PpcKsgbq_LfU8yG1pM',
    appId: '1:671548251869:android:b14e93883d93cddedbc534',
    messagingSenderId: '671548251869',
    projectId: 'robin-aad0d',
    storageBucket: 'robin-aad0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARZRme5cs7BPqq5A4ekmfxhsjr5L3b0YY',
    appId: '1:671548251869:ios:4216dec13f9303c1dbc534',
    messagingSenderId: '671548251869',
    projectId: 'robin-aad0d',
    storageBucket: 'robin-aad0d.firebasestorage.app',
    iosBundleId: 'com.example.robinProto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARZRme5cs7BPqq5A4ekmfxhsjr5L3b0YY',
    appId: '1:671548251869:ios:4216dec13f9303c1dbc534',
    messagingSenderId: '671548251869',
    projectId: 'robin-aad0d',
    storageBucket: 'robin-aad0d.firebasestorage.app',
    iosBundleId: 'com.example.robinProto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Ay3w2qM-sguKkaoTvCXEIedbNxpFKvg',
    appId: '1:671548251869:web:cbf1694c7bf24bf9dbc534',
    messagingSenderId: '671548251869',
    projectId: 'robin-aad0d',
    authDomain: 'robin-aad0d.firebaseapp.com',
    storageBucket: 'robin-aad0d.firebasestorage.app',
    measurementId: 'G-JPZ0Y5MNBG',
  );
}
